# Site settings
title: Junichi
subtitle: Shimizu
email: jun.shimi@kmd.keio.ac.jp
description: I’m a researcher in the filed of<br /> Wearable Computing / Human Computer Interaction / Eye tracking.
# baseurl: "/home" # the subpath of your site, e.g. /blog
url: "http://junichishmz.com" # the base hostname & protocol for your site
author:
street_address: Tokyo,Japan
city:
state: 
zip_code: 
country: 
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2


# Social settings
500px_url:
facebook_url: https://www.facebook.com/junichishz
github_url: https://github.com/junn511
gitlab_url: 
googleplus_url:
instagram_url: https://www.instagram.com/junn511/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/shimiii1

# Build settings
markdown: kramdown
