# Site settings
title: Junichi
subtitle: Shimizu
email: jun.shimi@kmd.keio.ac.jp
description: I’m a researcher in the filed of<br /> Wearable Computing / Human Computer Interaction / Eye tracking.
# baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "http://junichishmz.com" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
